// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {dvr} from '../models';
import {time} from '../models';
import {service} from '../models';
import {stream} from '../models';
import {store} from '../models';
import {weather} from '../models';

export function Boot():Promise<main.Boot>;

export function CopyText(arg1:string):Promise<void>;

export function DVR():Promise<dvr.State>;

export function DeleteRecording(arg1:string):Promise<void>;

export function DeleteRule(arg1:string):Promise<void>;

export function ExtendRecording(arg1:string,arg2:number):Promise<time.Time>;

export function Log(arg1:string,arg2:string):Promise<void>;

export function MarkWatched(arg1:string,arg2:boolean):Promise<void>;

export function Measure():Promise<service.SweepStatus>;

export function OpenURL(arg1:string):Promise<void>;

export function PlayRecording(arg1:string,arg2:number):Promise<stream.Playback>;

export function Record(arg1:dvr.Request):Promise<dvr.Rule>;

export function SaveProgress(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveSettings(arg1:store.Settings):Promise<main.Boot>;

export function Scan(arg1:boolean):Promise<service.Snapshot>;

export function ScanChannels():Promise<service.TunerInfo>;

export function SetConfig(arg1:service.Config):Promise<service.Config>;

export function SetDVRPrefs(arg1:dvr.Prefs):Promise<dvr.Prefs>;

export function SetZoom(arg1:number):Promise<void>;

export function Signal():Promise<service.SignalReport>;

export function StopRecording(arg1:string):Promise<void>;

export function StopTV():Promise<void>;

export function TestServer(arg1:string,arg2:string):Promise<service.Info>;

export function Tune(arg1:string):Promise<stream.Playback>;

export function UpdateRule(arg1:string,arg2:dvr.RuleUpdate):Promise<dvr.Rule>;

export function Weather():Promise<weather.Report>;
