// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Boot() {
  return window['go']['main']['App']['Boot']();
}

export function CopyText(arg1) {
  return window['go']['main']['App']['CopyText'](arg1);
}

export function DVR() {
  return window['go']['main']['App']['DVR']();
}

export function DeleteRecording(arg1) {
  return window['go']['main']['App']['DeleteRecording'](arg1);
}

export function DeleteRule(arg1) {
  return window['go']['main']['App']['DeleteRule'](arg1);
}

export function Log(arg1, arg2) {
  return window['go']['main']['App']['Log'](arg1, arg2);
}

export function MarkWatched(arg1, arg2) {
  return window['go']['main']['App']['MarkWatched'](arg1, arg2);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PlayRecording(arg1, arg2) {
  return window['go']['main']['App']['PlayRecording'](arg1, arg2);
}

export function Preview(arg1) {
  return window['go']['main']['App']['Preview'](arg1);
}

export function Profile(arg1, arg2, arg3) {
  return window['go']['main']['App']['Profile'](arg1, arg2, arg3);
}

export function Record(arg1) {
  return window['go']['main']['App']['Record'](arg1);
}

export function SaveProgress(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveProgress'](arg1, arg2, arg3);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function Scan(arg1) {
  return window['go']['main']['App']['Scan'](arg1);
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}

export function SetDVRPrefs(arg1) {
  return window['go']['main']['App']['SetDVRPrefs'](arg1);
}

export function SetZoom(arg1) {
  return window['go']['main']['App']['SetZoom'](arg1);
}

export function StopTV() {
  return window['go']['main']['App']['StopTV']();
}

export function TestServer(arg1, arg2) {
  return window['go']['main']['App']['TestServer'](arg1, arg2);
}

export function Tune(arg1) {
  return window['go']['main']['App']['Tune'](arg1);
}

export function UpdateRule(arg1, arg2) {
  return window['go']['main']['App']['UpdateRule'](arg1, arg2);
}

export function Weather() {
  return window['go']['main']['App']['Weather']();
}
